name: fnes
description: "A NES emulator written in Flutter."

publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.38.1

dependencies:
  equatable: ^2.0.7
  file_picker: ^10.3.6
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  mp_audio_stream: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: MonospaceFont
      fonts:
        - asset: assets/fonts/roboto_mono.ttf
