name: fnes
description: "A full-featured NES emulator with CPU, PPU, and APU support,
  built-in debugger, and cross-platform compatibility using Flutter."

publish_to: "none"
version: 0.8.5

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.38.1

dependencies:
  file_picker: ^10.3.7
  flutter:
    sdk: flutter
  mp_audio_stream: ^0.2.2
  shared_preferences: ^2.5.4
  signals: ^6.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: MonospaceFont
      fonts:
        - asset: assets/fonts/roboto_mono.ttf
